### ISSUE TITLE
add reference about this plugin to the main repository

### ISSUE THREAD

**Issue by sobolevn** [msilvestre/git-secret-diff#1]
Could please tell me, when this project is ready? I will add it to the docs.
Thanks!

**Comment by msilvestre** [comment]
2.0.0 was just released.

**Comment by sobolevn** [comment]
I have created a wiki page: https://github.com/sobolevn/git-secret/wiki/Third-party-plugins

Could you please add this plugin with: name, link and description. Thanks!
